package com.example.naebaecamteam1rm_spartube.search

val searchWordList: List<String> =
    listOf(
        "축구",
        "대한민국",
        "e스포츠",
        "금메달",
        "근대5종",
        "골프",
        "기계체조",
        "농구",
        "다이빙",
        "댄스 스포츠",
        "럭비",
        "리듬체조",
        "바둑",
        "배구",
        "배드민턴",
        "복싱",
        "사격",
        "수영",
        "승마",
        "클라이밍",
        "양궁",
        "역도",
        "요트",
        "육상",
        "조정",
        "주짓수",
        "리그 오브 레전드",
        "탁구",
        "태권도",
        "펜싱"
    )